# 50Wilu's Travis script taken from the FF2 Official GitHub repo. Adapted for VSH2 by Starblaster64 (blame this guy instead of Wilu if something breaks).

# Use the new container-based infrastructure
sudo: false

#Set lang
language: sourcepawn

# safelist
branches:
  only:
  - master
  - develop

# Install some apt packages needed for spcomp
addons:

    apt:
        packages:
            - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.8 # Stable
    - SMVERSION=1.9 # Unstable

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
before_script:
    - cd scripting/
    - wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc" -O include/tf2items.inc
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O include/morecolors.inc
    - wget "https://raw.githubusercontent.com/asherkin/SteamTools/master/plugin/steamtools.inc" -O include/steamtools.inc
    - wget "https://forums.alliedmods.net/attachment.php?attachmentid=116849&d=1377667508" -O include/tf2attributes.inc

    - chmod +x spcomp
    - mkdir compiled compiled/vsh2
script: ./compile.sh vsh2.sp

# Notifications
notifications:
email: false
